version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stockmaster_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stockmaster
      MYSQL_USER: stockmaster
      MYSQL_PASSWORD: stockmaster
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stockmaster_network

  redis:
    image: redis:7-alpine
    container_name: stockmaster_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stockmaster_network

  adminer:
    image: adminer:latest
    container_name: stockmaster_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - stockmaster_network

volumes:
  mysql_data:
  redis_data:

networks:
  stockmaster_network:
    driver: bridge
